### ISSUE TITLE
微信、ucweb不支持前端实现图片压缩上传

### ISSUE THREAD

**Issue by whitebaby** [whxaxes/node-test#1]
hi,你好：
           我用您的http://demo.wanghx.cn/uindex_2  做测试，在微信浏览器（小米3，微信6.3.7）和ucweb开发者版中，上传手机本地图片后，能够生成图片链接，但是图片0kb，也显示没有。
![772058857439917080](https://cloud.githubusercontent.com/assets/8775846/11176817/79ed9604-8c7b-11e5-88ee-778aa561230a.jpg)

**Comment by whxaxes** [comment]
该demo暂时没考虑android，该demo的图片上传采用xhr2.0上传塞了blob对象的formdata，因为android4.4以下的xhr2暂时不支持上传blob对象，所以是0kb，如果要考虑android的话，可能要把上传从blob对象改成base64字符串上传。

**Comment by whitebaby** [comment]
我用html5支持评测的数据得出可以安卓微信浏览器是支持blob的。测试页面：http://html5mark.com/?from=singlemessage&isappinstalled=1#~loop:svt=test 。我个人猜想可能是安卓版本在浏览器传输的时候，改了什么默认字符编码方式。我的另外一个帖子里面（https://github.com/leancloud/javascript-sdk/issues/148#issuecomment-156941201），也有类似的情况，直接就用的base64，也还是不行。小米默认的浏览器就没有此类问题。第一个图片是支持接口的截图，第二个图片是小米3默认浏览器成功上传的截图。
![217180577618077620](https://cloud.githubusercontent.com/assets/8775846/11177726/8c30b254-8c82-11e5-8bc4-359b17d33c13.jpg)
![772058857439917080](https://cloud.githubusercontent.com/assets/8775846/11177804/2935f8c0-8c83-11e5-8ff1-7fd22f8872d3.jpg)

**Comment by whxaxes** [comment]
我没说android不支持blob对象，我是说android的xhr不支持上传blob对象
![image](https://cloud.githubusercontent.com/assets/5856440/11179609/9c4a7da2-8c8f-11e5-9e26-c8e6820d5ed5.png)

**Comment by whxaxes** [comment]
小米3 base64上传的问题，我没试过呢，最近比较忙，有空再试一下

**Comment by dreamer2012** [comment]
同现出Android微信上传数据为0的情况，不知道后续怎么解决的。

**Comment by whxaxes** [comment]
代码有更新，尝试了一下 http://stackoverflow.com/questions/15639070/empty-files-uploaded-in-android-native-browser/28809955#28809955   这里在android平台的解决方案
