### ISSUE TITLE
请问下MB前的计算里先乘以10再除以10是有什么特别的考虑吗

### ISSUE THREAD

**Issue by Yakima-Teng** [whxaxes/node-test#11]
https://github.com/whxaxes/node-test/blob/9f49c72cd68d1300a5d28f5b3d10ab1fe5caf781/server/upload/index_2.html#L77

请问下MB前的计算里先乘以10再除以10是有什么特别的考虑吗

**Comment by whxaxes** [comment]
保留一位小数取整
