### ISSUE TITLE
关于 creeper

### ISSUE THREAD

**Issue by AngusFu** [whxaxes/node-test#5]
您的 creeper 爬虫代码让我收获良多。大概是一年前看到您的代码和线上页面，之后再自己的电脑上跑起了代码，加入了自己常看的网址，上班空闲时间总会刷刷，学到了很多，成长非常大。非常感谢！

最近闲着在您思路的基础上，做了一个简单的 [chrome extension](https://github.com/AngusFu/chrome-creeper)，主要起作用的部分还是 creeper 下面 source.js。考虑到主要还是使用的您的代码，因此在您这里提个 issue 说明一下。非常感谢您的项目！

关于您的 creeper爬虫这个，使用时有一点比较纠结的是有些博客升到了 https，这样就爬不下来了。

另外，一些网站（http）可能是使用了反爬虫的机制（？），有时候爬不出来，后来我也试着用另一个叫 node-grass 的包来替代您的 transdata，效果也不太理想，一些 node-grass能爬的 transdata 爬不下来，反之亦然。

上面说的两点也是促使我去做 chrome extension 的原因的一部分。

PS：代码中其中关于爬虫解析、redis缓存以及模块热替换等等这样一些东西，也让我受益匪浅。

再次感谢您的 nodejs 爬虫代码！

**Comment by whxaxes** [comment]
哈，能对你有帮助我也很开心，有些网站如果是动态生成的确实不好爬，但是大部分博客类网站都是欢迎别人爬取的，所以我之前写的时候倒没遇到啥问题，https的话transdata确实不支持，这个组件写的比较简陋，你可以用一些比较成熟的组件比如[superagent](https://github.com/visionmedia/superagent)或者[urllib](https://github.com/node-modules/urllib)之类的
