### ISSUE TITLE
上传图片时如何修改图片的filename

### ISSUE THREAD

**Issue by Yeahax** [whxaxes/node-test#6]
按照demo上传图片，但是上传过去的图片filename总是一样的，应该怎样修改？
![image](https://cloud.githubusercontent.com/assets/8794879/20697283/dbfdd1ce-b632-11e6-84cf-cd84eb5549d8.png)

**Comment by whxaxes** [comment]
`formData.append(name, value, filename);`

**Comment by Yeahax** [comment]
Thank!问题已解决
